
default:

  debug_mode: False

  app:
    name: "Outlook"
    description: "Microsoft Outlook is an email and calendar app that lets users read and send mail, manage calendars, contacts, and notifications."

  driver:
    device_id: "R3CX20L5N6F"
    os_name: "android"
    appPackage: "com.microsoft.office.outlook"
    appActivity: "com.acompli.acompli.CentralActivity"
    skip_exploration_for_no_app_package: true # If true, skip exploration when not in the Outlook app package (e.g., after navigating away).
    reset_instruction: "Go to Mail (bottom bar). Check the top inbox filter: if Focused is already white/active, do not tap it (tapping may switch to Other). Tap Focused only if Other is selected. When Mail is open and Focused is white/active, terminate with success."
    use_launcher_intent: true

  vlm:
    alibaba_api_key: 'sk-9e08c5810b434d9db9a335e1cca2a02a'
    yibu_api_key: 'sk-RBKsBNgCvZPw61tyyJjZZS78ewggEyoTDIRCtZ5hxKVqQpHa'
    use_yibu_api: true

  agent:
    verbose_print: false
    url: "http://10.218.163.104:8000/v1"
    model_name: "mai_ui"
    settings: 
      history_n: 3
      resize_factor: 0.5
      model_thinking: true
      max_tokens_no_thinking: 128
    max_steps: 10

  logs:
    root: "../exploration/explored_apps/outlook"
    resume_from_checkpoint: true

  batch_mode: true
  input_dir: "/home/mehdi/Downloads/AgentNavigatorDataset/DATA/outlook_5.2604.1/"
  output_dir: "./results"

  use_memory_for_navigation: true
  query: "Navigate to the Feedback to Microsoft page."
  top_k_in_first_stage_retrieval: 30
  top_k_retrieval_in_stage_2: 5
  pick_candidate_index: 0    # 0 means best candidate, 1 means second best, ... -1 means use gradio to pick candidate  (has to be less than top_k_retrieval_in_stage_2)




