default:

  debug_mode: False


  app:
    name: "Youtube"
    description: "YouTube is a video-sharing platform that allows users to watch and share videos."

  driver:
    device_id: "R3CX20L5N6F"
    os_name: "android"
    appPackage: "com.google.android.youtube"
    appActivity: "com.google.android.youtube.app.honeycomb.Shell$HomeActivity"
    skip_exploration_for_no_app_package: true # so if this is True we skip exploration if we are not in the app package for example if we are in clock app and we opened browser (using help button  we don't want to explore there or if we land on home screen))
    use_launcher_intent: true
  vlm:
    alibaba_api_key: 'sk-9e08c5810b434d9db9a335e1cca2a02a'
    yibu_api_key: 'sk-caIdHUNLbUgJ4vpB3LFT2FQhpV4ELNgmL5PXBGgJq1kvLL8C'
    use_yibu_api: true

  agent:
    verbose_print: false
    url: "http://10.193.241.177:8089/v1"
    model_name: "mai_ui"
    settings: 
      history_n: 3
      resize_factor: 0.75
    max_steps: 10

  logs:
    root: "../exploration/explored_apps/youtube"
    resume_from_checkpoint: true

  batch_mode: false
  input_dir: "/home/mehdi/Downloads/AgentNavigatorDataset/DATA/outlook_5.2604.1/"
  output_dir: "./results"

  use_memory_for_navigation: true
  query: "Navigate to the notifications settings page."
  top_k_in_first_stage_retrieval: 30
  top_k_retrieval_in_stage_2: 5
  pick_candidate_index: 0    # 0 means best candidate, 1 means second best, ... -1 means use gradio to pick candidate  (has to be less than top_k_retrieval_in_stage_2)


