
default:

  debug_mode: False

  app:
    name: "Zhixing Train Tickets"
    description: "Zhixing Train Tickets is a travel and transportation application for searching, booking, and managing train tickets in China. The app supports ticket queries, seat availability checks, booking and payment, order management, and travel reminders, offering a streamlined interface for railway travel planning."

  driver:
    device_id: "3AP0224B05003112"
    os_name: "harmony"
    appPackage: "com.suanya.harmonynext"
    appActivity: "PhoneAbility"
    skip_exploration_for_no_app_package: true
    reset_instruction: "Go to Home (main bottom bar left icon) then tap on train subtab on the top nav bar. If they are already active, terminate with success. If there is an advertisement close it."

  vlm:
    alibaba_api_key: 'sk-9e08c5810b434d9db9a335e1cca2a02a'
    yibu_api_key: 'sk-caIdHUNLbUgJ4vpB3LFT2FQhpV4ELNgmL5PXBGgJq1kvLL8C'
    use_yibu_api: true

  agent:
    verbose_print: false
    url: "http://10.193.241.177:8089/v1"
    model_name: "mai_ui"
    settings:
      history_n: 3
      resize_factor: 0.75
    max_steps: 10

  logs:
    root: "../exploration/explored_apps/zhixing_train_harmony"
    resume_from_checkpoint: true

  batch_mode: false
  output_dir: "./results"

  use_memory_for_navigation: true
  query: "Navigate to the train ticket search page."
  top_k_in_first_stage_retrieval: 30
  top_k_retrieval_in_stage_2: 5
  pick_candidate_index: 0    # 0 means best candidate, 1 means second best, ... -1 means use gradio to pick candidate  (has to be less than top_k_retrieval_in_stage_2)
